export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCSESS = 'ORDER_CREATE_SUCCSESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCSESS = 'ORDER_DETAILS_SUCCSESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCSESS = 'ORDER_PAY_SUCCSESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET = 'ORDER_PAY_RESET';

export const ORDER_MYORDERS_REQUEST = 'ORDER_MYORDERS_REQUEST';
export const ORDER_MYORDERS_SUCCSESS = 'ORDER_MYORDERS_SUCCSESS';
export const ORDER_MYORDERS_FAIL = 'ORDER_MYORDERS_FAIL';
export const ORDER_MYORDERS_RESET = 'ORDER_MYORDERS_RESET';

export const ORDER_USER_REQUEST = 'ORDER_USER_REQUEST';
export const ORDER_USER_SUCCSESS = 'ORDER_USER_SUCCSESS';
export const ORDER_USER_FAIL = 'ORDER_USER_FAIL';

export const ORDER_DELIVERED_REQUEST = 'ORDER_DELIVERED_REQUEST';
export const ORDER_DELIVERED_SUCCSESS = 'ORDER_DELIVERED_SUCCSESS';
export const ORDER_DELIVERED_FAIL = 'ORDER_DELIVERED_FAIL';
export const ORDER_DELIVERED_RESET = 'ORDER_DELIVERED_RESET';
